function GeneratorsI(mode: longint; arg: longint): longint; cdecl;
function GeneratorsF(mode: longint; arg: double): double; cdecl;
function GeneratorsS(mode: longint; arg: pAnsiChar): pAnsiChar; cdecl;
procedure GeneratorsV(mode: longint; out arg:variant); cdecl;
function GeneratorsI(mode: longint; arg: longint): longint; cdecl;
function GeneratorsF(mode: longint; arg: double): double; cdecl;
function GeneratorsS(mode: longint; arg: pAnsiChar): pAnsiChar; cdecl;
procedure GeneratorsV(mode: longint; out arg:variant); cdecl;
function DSSI(mode:longint;arg:longint):longint;cdecl;
function DSSS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure DSSV(mode:longint;out arg:variant);cdecl;
function DSSI(mode:longint;arg:longint):longint;cdecl;
function DSSS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure DSSV(mode:longint;out arg:variant);cdecl;
function SolutionI(mode:longint; arg: longint):longint; cdecl;
function SolutionF(mode:longint; arg: double):double; cdecl;
function SolutionS(mode:longint; arg: pAnsiChar):pAnsiChar; cdecl;
procedure SolutionV(mode:longint; out arg:Variant); cdecl;
function SolutionI(mode:longint; arg: longint):longint; cdecl;
function SolutionF(mode:longint; arg: double):double; cdecl;
function SolutionS(mode:longint; arg: pAnsiChar):pAnsiChar; cdecl;
procedure SolutionV(mode:longint; out arg:Variant); cdecl;
function DSSLoads(mode:longint; arg:longint):longint; cdecl;
function DSSLoadsF(mode:longint; arg:double):double; cdecl;
function DSSLoadsS(mode:longint; arg:pAnsiChar):pAnsiChar; cdecl;
procedure DSSLoadsV(mode:longint; out arg:variant); cdecl;
function DSSLoads(mode:longint; arg: longint):longint; cdecl;
function DSSLoadsF(mode:longint; arg:double):double; cdecl;
function DSSLoadsS(mode:longint; arg:pAnsiChar):pAnsiChar; cdecl;
procedure DSSLoadsV(mode:longint; out arg:variant); cdecl;
function LineCodesI(mode: longint; arg: longint): longint; cdecl;
function LineCodesF(mode: longint; arg: double): double; cdecl;
function LineCodesS(mode: longint; arg: pAnsiChar): pAnsiChar; cdecl;
procedure LineCodesV(mode: longint; out arg:variant);cdecl;
function LineCodesI(mode: longint; arg: longint): longint; cdecl;
function LineCodesF(mode: longint; arg: double): double; cdecl;
function LineCodesS(mode: longint; arg: pAnsiChar): pAnsiChar; cdecl;
procedure LineCodesV(mode: longint; out arg:variant);cdecl;
function IsourceI(mode:longint;arg:longint):Longint;cdecl;
function IsourceF(mode:longint;arg:double):double;cdecl;
function IsourceS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure IsourceV(mode:longint;out arg:variant);cdecl;
function IsourceI(mode:longint;arg:longint):Longint;cdecl;
function IsourceF(mode:longint;arg:double):double;cdecl;
function IsourceS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure IsourceV(mode:longint;out arg:variant);cdecl;
function DSSElementI(mode:longint; arg: longint):longint;cdecl;
function DSSElementS(mode:longint; arg: pAnsiChar):pAnsiChar;cdecl;
procedure DSSElementV(mode: longint; out arg:variant);cdecl;
function DSSElementI(mode:longint; arg: longint):longint;cdecl;
function DSSElementS(mode:longint; arg: pAnsiChar):pAnsiChar;cdecl;
procedure DSSElementV(mode: longint; out arg:variant);cdecl;
function LoadShapeI(mode:longint; arg:longint):longint;cdecl;
function LoadShapeF(mode:longint; arg:double):double;cdecl;
function LoadShapeS(mode:longint; arg:pAnsiChar):pAnsiChar;cdecl;
procedure LoadShapeV(mode:longint; out arg:variant);cdecl;
function LoadShapeI(mode:longint; arg:longint):longint;cdecl;
function LoadShapeF(mode:longint; arg:double):double;cdecl;
function LoadShapeS(mode:longint; arg:pAnsiChar):pAnsiChar;cdecl;
procedure LoadShapeV(mode:longint; out arg:variant);cdecl;
function DSSExecutiveI(mode:longint; arg:longint):longint;cdecl;
function DSSExecutiveS(mode:longint; arg:pAnsiChar):pAnsiChar;cdecl;
function DSSExecutiveI(mode:longint; arg:longint):longint;cdecl;
function DSSExecutiveS(mode:longint; arg:pAnsiChar):pAnsiChar;cdecl;
function PVsystemsI(mode:longint;arg:longint):longint;cdecl;
function PVsystemsF(mode:longint;arg:double):double;cdecl;
function PVsystemsS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure PVsystemsV(mode:longint;out arg:variant);cdecl;
function PVsystemsI(mode:longint;arg:longint):longint;cdecl;
function PVsystemsF(mode:longint;arg:double):double;cdecl;
function PVsystemsS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure PVsystemsV(mode:longint;out arg:variant);cdecl;
function VsourcesI(mode:longint;arg:longint):Longint;cdecl;
function VsourcesF(mode:longint;arg:double):double;cdecl;
function VsourcesS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure VsourcesV(mode:longint;out arg:variant);cdecl;
function VsourcesI(mode:longint;arg:longint):Longint;cdecl;
function VsourcesF(mode:longint;arg:double):double;cdecl;
function VsourcesS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure VsourcesV(mode:longint;out arg:variant);cdecl;
function CapacitorsI(mode:longint; arg: longint):longint;cdecl;
function CapacitorsF(mode:longint; arg: double):double;cdecl;
function CapacitorsS(mode:longint; arg: pAnsiChar):pAnsiChar;cdecl;
procedure CapacitorsV(mode:longint; out arg:variant);cdecl;
function CapacitorsI(mode:longint; arg: longint):longint;cdecl;
function CapacitorsF(mode:longint; arg: double):double;cdecl;
function CapacitorsS(mode:longint; arg: pAnsiChar):pAnsiChar;cdecl;
procedure CapacitorsV(mode:longint; out arg:variant);cdecl;
function XYCurvesI(mode:longint;arg:longint):longint;cdecl;
function XYCurvesF(mode:longint;arg:double):double;cdecl;
function XYCurvesS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure XYCurvesV(mode:longint; var arg:variant);cdecl;
function XYCurvesI(mode:longint;arg:longint):longint;cdecl;
function XYCurvesF(mode:longint;arg:double):double;cdecl;
function XYCurvesS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure XYCurvesV(mode:longint; var arg:variant);cdecl;
function DSSProgressI(mode: longint; arg: longint): longint; cdecl;
function DSSProgressS(mode: longint; arg: pAnsiChar): pAnsiChar; cdecl;
function DSSProgressI(mode: longint; arg: longint): longint; cdecl;
function DSSProgressS(mode: longint; arg: pAnsiChar): pAnsiChar; cdecl;
function DSSProperties(mode:longint; arg:pAnsiChar):pAnsiChar; cdecl;
function DSSProperties(mode:longint; arg:pAnsiChar):pAnsiChar; cdecl;
function ErrorDesc():pAnsiChar;cdecl;
function ErrorCode():longint;cdecl;
function ErrorCode():longint;cdecl;
function ErrorDesc():pAnsiChar;cdecl;
Function  InitAndGetYparams(var hY:NativeUInt; var nBus, nNZ:LongWord): Longword; cdecl;
Procedure GetCompressedYMatrix(hY:NativeUInt; nBus, nNz:Longword; Var ColPtr, RowIdx:pIntegerArray; Var cVals:pComplexArray); cdecl;
procedure ZeroInjCurr; cdecl;
procedure GetSourceInjCurrents; cdecl;
procedure GetPCInjCurr; cdecl;
function SystemYChanged(mode, arg: longint): longint; cdecl;
procedure BuildYMatrixD(BuildOps, AllocateVI: longint); cdecl;
function UseAuxCurrents(mode, arg: longint): longint; cdecl;
procedure AddInAuxCurrents(SType: integer); cdecl;
procedure getIpointer(var IvectorPtr: pNodeVarray);cdecl;
procedure getVpointer(var VvectorPtr: pNodeVarray);cdecl;
function SolveSystem(var NodeV:pNodeVarray): integer; cdecl;
Function InitAndGetYparams(var hY:NativeUInt; var nBus, nNZ:LongWord): Longword; cdecl;
Procedure GetCompressedYMatrix(hY:NativeUInt; nBus, nNz:Longword; Var ColPtr, RowIdx:pIntegerArray; Var cVals:pComplexArray); cdecl;
procedure ZeroInjCurr; cdecl;
procedure GetSourceInjCurrents; cdecl;
procedure GetPCInjCurr; cdecl;
function SystemYChanged(mode, arg: longint): longint; cdecl;
procedure BuildYMatrixD(BuildOps, AllocateVI: longint); cdecl;
function UseAuxCurrents(mode, arg: longint): longint; cdecl;
procedure AddInAuxCurrents(SType: integer); cdecl;
procedure getIpointer(var IvectorPtr: pNodeVarray);cdecl;
procedure getVpointer(var VvectorPtr: pNodeVarray);cdecl;
function SolveSystem(var NodeV:pNodeVarray): integer; cdecl;
function SwtControlsI(mode: longint; arg: longint): longint; cdecl;
function SwtControlsF(mode: longint; arg: double): double; cdecl;
function SwtControlsS(mode: longint; arg: pAnsiChar): pAnsiChar; cdecl;
procedure SwtControlsV(mode: longint; out arg: variant); cdecl;
function SwtControlsI(mode: longint; arg: longint): longint; cdecl;
function SwtControlsF(mode: longint; arg: double): double; cdecl;
function SwtControlsS(mode: longint; arg: pAnsiChar): pAnsiChar; cdecl;
procedure SwtControlsV(mode: longint; out arg: variant); cdecl;
function BUSI(mode: longint; arg: longint): longint; cdecl;
function BUSF(mode: longint; arg: double): double; cdecl;
function BUSS(mode: longint; arg: pAnsiChar): pAnsiChar; cdecl;
procedure BUSV(mode: longint; out arg:Variant); cdecl;
function BUSI(mode: longint; arg: longint): longint; cdecl;
function BUSF(mode: longint; arg: double): double; cdecl;
function BUSS(mode: longint; arg: pAnsiChar): pAnsiChar; cdecl;
procedure BUSV(mode: longint; out arg:Variant); cdecl;
function DSSPut_Command(a:PAnsiChar):PAnsiChar;cdecl;
function DSSPut_Command(a:PAnsiChar):PAnsiChar;cdecl;
function CircuitI(mode:longint; arg: longint):longint;cdecl;
function CircuitF(mode:longint; arg1, arg2: double):double;cdecl;
function CircuitS(mode:longint; arg: pAnsiChar):pAnsiChar;cdecl;
procedure CircuitV(mode:longint; out arg:variant; arg2: longint);cdecl;
function CircuitI(mode:longint; arg: longint):longint;cdecl;
function CircuitF(mode:longint; arg1, arg2: double):double;cdecl;
function CircuitS(mode:longint; arg: pAnsiChar):pAnsiChar;cdecl;
procedure CircuitV(mode:longint; out arg:variant; arg2: longint);cdecl;
function CmathLibF(mode:longint; arg1:double; arg2:double):double;cdecl;
procedure CmathLibV(mode:longint; Realpart:double; ImagPart:double; out arg: variant);cdecl;
function CmathLibF(mode:longint; arg1:double; arg2:double):double;cdecl;
procedure CmathLibV(mode:longint; Realpart:double; ImagPart:double; out arg: variant);cdecl;
function CktElementI(mode:longint; arg:longint):longint;cdecl;
function CktElementF(mode:longint; arg:double):double;cdecl;
function CktElementS(mode:longint; arg:pAnsiChar):pAnsiChar;cdecl;
procedure CktElementV(mode:longint; out arg:variant);cdecl;
function CktElementI(mode:longint; arg:longint):longint;cdecl;
function CktElementF(mode:longint; arg:double):double;cdecl;
function CktElementS(mode:longint; arg:pAnsiChar):pAnsiChar;cdecl;
procedure CktElementV(mode:longint; out arg:variant);cdecl;
function ReclosersI(mode:longint;arg:longint):longint;cdecl;
function ReclosersF(mode:longint;arg:double):double;cdecl;
function ReclosersS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure ReclosersV(mode:longint;out arg:variant);cdecl;
function ReclosersI(mode:longint;arg:longint):longint;cdecl;
function ReclosersF(mode:longint;arg:double):double;cdecl;
function ReclosersS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure ReclosersV(mode:longint;out arg:variant);cdecl;
function ActiveClassI(mode:longint; arg: longint):longint; cdecl;
function ActiveClassS(mode:longint; arg: pAnsiChar):pAnsiChar; cdecl;
procedure ActiveClassV(mode:longint; out arg:variant); cdecl;
function ActiveClassI(mode:longint; arg: longint):longint; cdecl;
function ActiveClassS(mode:longint; arg: pAnsiChar):pAnsiChar; cdecl;
procedure ActiveClassV(mode:longint; out arg:variant); cdecl;
function RelaysI(mode:longint;arg:longint):longint;cdecl;
function RelaysS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure RelaysV(mode:longint;out arg:variant);cdecl;
function RelaysI(mode:longint;arg:longint):longint;cdecl;
function RelaysS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure RelaysV(mode:longint;out arg:variant);cdecl;
function ParserI(mode: longint; arg:longint):longint;cdecl;
function ParserF(mode: longint; arg:double):double;cdecl;
function ParserS(mode: longint; arg:pAnsiChar):pAnsiChar;cdecl;
procedure ParserV(mode: longint; var arg:variant);cdecl; // sometimes ParserV uses the input arg value
function ParserI(mode: longint; arg:longint):longint;cdecl;
function ParserF(mode: longint; arg:double):double;cdecl;
function ParserS(mode: longint; arg:pAnsiChar):pAnsiChar;cdecl;
procedure ParserV(mode: longint; var arg:variant);cdecl;
function CapControlsI(mode:longint; arg:longint):longint;cdecl;
function CapControlsF(mode:longint; arg:double):double;cdecl;
function CapControlsS(mode:longint; arg:pAnsiChar):pAnsiChar;cdecl;
procedure CapControlsV(mode:longint; out arg:variant);cdecl;
function CapControlsI(mode:longint; arg:longint):longint;cdecl;
function CapControlsF(mode:longint; arg:double):double;cdecl;
function CapControlsS(mode:longint; arg:pAnsiChar):pAnsiChar;cdecl;
procedure CapControlsV(mode:longint; out arg:variant);cdecl;
function RegControlsI(mode: longint; arg: longint):longint ;cdecl;
function RegControlsF(mode: longint; arg: double):double ;cdecl;
function RegControlsS(mode: longint; arg: pAnsiChar):pAnsiChar ;cdecl;
procedure RegControlsV(mode: longint; out arg: variant) ;cdecl;
function RegControlsI(mode: longint; arg: longint):longint ;cdecl;
function RegControlsF(mode: longint; arg: double):double ;cdecl;
function RegControlsS(mode: longint; arg: pAnsiChar):pAnsiChar ;cdecl;
procedure RegControlsV(mode: longint; out arg: variant) ;cdecl;
function MetersI(mode: longint; arg: longint):Longint;cdecl;
function MetersF(mode: longint; arg: double):double;cdecl;
function MetersS(mode: longint; arg: pAnsiChar):pAnsiChar;cdecl;
procedure MetersV(mode: longint; out arg:variant);cdecl;
function MetersI(mode: longint; arg: longint):Longint;cdecl;
function MetersF(mode: longint; arg: double):double;cdecl;
function MetersS(mode: longint; arg: pAnsiChar):pAnsiChar;cdecl;
procedure MetersV(mode: longint; out arg:variant);cdecl;
function PDElementsI(mode:longint; arg:longint):longint;cdecl;
function PDElementsF(mode:longint; arg:double):double;cdecl;
function PDElementsS(mode:longint; arg:pAnsiChar):pAnsiChar;cdecl;
function PDElementsI(mode:longint; arg:longint):longint;cdecl;
function PDElementsF(mode:longint; arg:double):double;cdecl;
function PDElementsS(mode:longint; arg:pAnsiChar):pAnsiChar;cdecl;
function TransformersI(mode: longint; arg: longint):longint; cdecl;
function TransformersF(mode: longint; arg: double):double; cdecl;
function TransformersS(mode: longint; arg: pAnsiChar):pAnsiChar; cdecl;
procedure TransformersV(mode: longint; out arg: variant); cdecl;
function TransformersI(mode: longint; arg: longint):longint; cdecl;
function TransformersF(mode: longint; arg: double):double; cdecl;
function TransformersS(mode: longint; arg: pAnsiChar):pAnsiChar; cdecl;
procedure TransformersV(mode: longint; out arg: variant); cdecl;
function SettingsI(mode: longint; arg: longint):longint;cdecl;
function SettingsF(mode: longint; arg: double):double;cdecl;
function SettingsS(mode: longint; arg: pAnsiChar):pAnsiChar;cdecl;
procedure SettingsV(mode:longint; out arg:variant); cdecl;
function SettingsI(mode: longint; arg: longint):longint;cdecl;
function SettingsF(mode: longint; arg: double):double;cdecl;
function SettingsS(mode: longint; arg: pAnsiChar):pAnsiChar;cdecl;
procedure SettingsV(mode:longint; out arg:variant); cdecl;
function MonitorsI(mode:longint; arg: longint):longint; cdecl;
function MonitorsS(mode:longint; arg: pAnsiChar):pAnsiChar; cdecl;
procedure MonitorsV(mode:longint; out arg:variant); cdecl;
function MonitorsI(mode:longint; arg: longint):longint; cdecl;
function MonitorsS(mode:longint; arg: pAnsiChar):pAnsiChar; cdecl;
procedure MonitorsV(mode:longint; out arg:variant); cdecl;
function SensorsI(mode:longint; arg:longint):longint;cdecl;
function SensorsF(mode:longint; arg:double):double;cdecl;
function SensorsS(mode:longint; arg:pAnsiChar):pAnsiChar;cdecl;
procedure SensorsV(mode:longint; out arg:variant);cdecl;
function SensorsI(mode:longint; arg:longint):longint;cdecl;
function SensorsF(mode:longint; arg:double):double;cdecl;
function SensorsS(mode:longint; arg:pAnsiChar):pAnsiChar;cdecl;
procedure SensorsV(mode:longint; out arg:variant);cdecl;
function FusesI(mode:longint;arg:longint):longint;cdecl;
function FusesF(mode:longint;arg:double):double;cdecl;
function FusesS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure FusesV(mode:longint;out arg:variant);cdecl;
function FusesI(mode:longint;arg:longint):longint;cdecl;
function FusesF(mode:longint;arg:double):double;cdecl;
function FusesS(mode:longint;arg:pAnsiChar):pAnsiChar;cdecl;
procedure FusesV(mode:longint;out arg:variant);cdecl;
function LinesI(mode: longint; arg: longint): longint; cdecl;
function LinesF(mode: longint; arg: double): double; cdecl;
function LinesS(mode: longint; arg: pAnsiChar): pAnsiChar; cdecl;
procedure LinesV(mode: longint; out arg:variant);cdecl;
function LinesI(mode: longint; arg: longint): longint; cdecl;
function LinesF(mode: longint; arg: double): double; cdecl;
function LinesS(mode: longint; arg: pAnsiChar): pAnsiChar; cdecl;
procedure LinesV(mode: longint; out arg:variant);cdecl;
function TopologyI(mode:longint; arg:longint):longint;cdecl;
function TopologyS(mode:longint; arg:pAnsiChar):pAnsiChar;cdecl;
procedure TopologyV(mode:longint; out arg:variant);cdecl;
function TopologyI(mode:longint; arg:longint):longint;cdecl;
function TopologyS(mode:longint; arg:pAnsiChar):pAnsiChar;cdecl;
procedure TopologyV(mode:longint; out arg:variant);cdecl;
function CtrlQueueI(mode: longint; arg: longint):longint;cdecl;
procedure CtrlQueueV(mode:longint; out arg:variant);cdecl;
function CtrlQueueI(mode: longint; arg: longint):longint;cdecl;
procedure CtrlQueueV(mode:longint; out arg:variant);cdecl;